---
common:
  site_url: http://mail-manager.dev
  unsubscribe_path: /listmgr
  subscribe_path: /subscribe
  double_opt_in_path: /listmgr/confirm
  dont_include_images_domains:
  - yahoo.com
  - google.com
  - hotmail.com
  sleep_time_between_messages: 0.3
  public_layout: mail_manager/layout
  table_prefix: mail_manager_
  default_from_email_address: chrisboy <chrisboy@lvh.me>
  signup_email_address: chrisboy <chrisboy@lvh.me>
  secret: 7a3906324erwr6254e85e4bdb80592001a
  exception_notification:
    to_addresses:
      - chauboldt@lone-star.net
      - chauboldt@lnstar.com
    from_address:
      errors@example.net
  bounce:
    email_address: bounce@lvh.me
    login: bounce
    password: secret
    pop_server: mail.lvh.me
    port: <%= ENV['POST_OFFICE_POP_PORT'] %>
    ssl: false
    tls: false
    enable_starttls_auto: false
test:
  site_url: http://mail-manager.lvh.me:4460
